version: '3.8'
services:
  db:
    container_name: container-pg
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  server:
    container_name: eth-fetcher
    image:  ethfetcher
    hostname: localhost
    ports:
      - "8080:8080"
    environment:
      ETH_NODE_URL: https://goerli.infura.io/v3/ef391c6c612f48f88cae26bc256487be
      DB_CONNECTION_URL: postgresql://admin:root@db:5432/postgres
      API_PORT: 8080
    links:
      - db

volumes:
  postgres-data: