// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	handlers "eth-fetcher/handlers"
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// handleFunc is an autogenerated mock type for the handleFunc type
type handleFunc struct {
	mock.Mock
}

type handleFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *handleFunc) EXPECT() *handleFunc_Expecter {
	return &handleFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *handleFunc) Execute(_a0 handlers.Session, _a1 *http.Request) (interface{}, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(handlers.Session, *http.Request) (interface{}, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(handlers.Session, *http.Request) interface{}); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(handlers.Session, *http.Request) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// handleFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type handleFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 handlers.Session
//   - _a1 *http.Request
func (_e *handleFunc_Expecter) Execute(_a0 interface{}, _a1 interface{}) *handleFunc_Execute_Call {
	return &handleFunc_Execute_Call{Call: _e.mock.On("Execute", _a0, _a1)}
}

func (_c *handleFunc_Execute_Call) Run(run func(_a0 handlers.Session, _a1 *http.Request)) *handleFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(handlers.Session), args[1].(*http.Request))
	})
	return _c
}

func (_c *handleFunc_Execute_Call) Return(_a0 interface{}, _a1 error) *handleFunc_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *handleFunc_Execute_Call) RunAndReturn(run func(handlers.Session, *http.Request) (interface{}, error)) *handleFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newHandleFunc creates a new instance of handleFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newHandleFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *handleFunc {
	mock := &handleFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
