// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	models "eth-fetcher/database/models"

	mock "github.com/stretchr/testify/mock"
)

// DB is an autogenerated mock type for the DB type
type DB struct {
	mock.Mock
}

type DB_Expecter struct {
	mock *mock.Mock
}

func (_m *DB) EXPECT() *DB_Expecter {
	return &DB_Expecter{mock: &_m.Mock}
}

// AddUserTransactions provides a mock function with given fields: userID, transactions
func (_m *DB) AddUserTransactions(userID string, transactions []*models.Transaction) error {
	ret := _m.Called(userID, transactions)

	if len(ret) == 0 {
		panic("no return value specified for AddUserTransactions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []*models.Transaction) error); ok {
		r0 = rf(userID, transactions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DB_AddUserTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserTransactions'
type DB_AddUserTransactions_Call struct {
	*mock.Call
}

// AddUserTransactions is a helper method to define mock.On call
//   - userID string
//   - transactions []*models.Transaction
func (_e *DB_Expecter) AddUserTransactions(userID interface{}, transactions interface{}) *DB_AddUserTransactions_Call {
	return &DB_AddUserTransactions_Call{Call: _e.mock.On("AddUserTransactions", userID, transactions)}
}

func (_c *DB_AddUserTransactions_Call) Run(run func(userID string, transactions []*models.Transaction)) *DB_AddUserTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]*models.Transaction))
	})
	return _c
}

func (_c *DB_AddUserTransactions_Call) Return(_a0 error) *DB_AddUserTransactions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DB_AddUserTransactions_Call) RunAndReturn(run func(string, []*models.Transaction) error) *DB_AddUserTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with given fields:
func (_m *DB) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DB_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type DB_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *DB_Expecter) Close() *DB_Close_Call {
	return &DB_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *DB_Close_Call) Run(run func()) *DB_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DB_Close_Call) Return(_a0 error) *DB_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DB_Close_Call) RunAndReturn(run func() error) *DB_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllTransactions provides a mock function with given fields:
func (_m *DB) GetAllTransactions() ([]*models.Transaction, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllTransactions")
	}

	var r0 []*models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*models.Transaction, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.Transaction); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DB_GetAllTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTransactions'
type DB_GetAllTransactions_Call struct {
	*mock.Call
}

// GetAllTransactions is a helper method to define mock.On call
func (_e *DB_Expecter) GetAllTransactions() *DB_GetAllTransactions_Call {
	return &DB_GetAllTransactions_Call{Call: _e.mock.On("GetAllTransactions")}
}

func (_c *DB_GetAllTransactions_Call) Run(run func()) *DB_GetAllTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DB_GetAllTransactions_Call) Return(_a0 []*models.Transaction, _a1 error) *DB_GetAllTransactions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DB_GetAllTransactions_Call) RunAndReturn(run func() ([]*models.Transaction, error)) *DB_GetAllTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransactionsByHashes provides a mock function with given fields: hashes
func (_m *DB) GetTransactionsByHashes(hashes []string) ([]*models.Transaction, error) {
	ret := _m.Called(hashes)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionsByHashes")
	}

	var r0 []*models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func([]string) ([]*models.Transaction, error)); ok {
		return rf(hashes)
	}
	if rf, ok := ret.Get(0).(func([]string) []*models.Transaction); ok {
		r0 = rf(hashes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(hashes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DB_GetTransactionsByHashes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactionsByHashes'
type DB_GetTransactionsByHashes_Call struct {
	*mock.Call
}

// GetTransactionsByHashes is a helper method to define mock.On call
//   - hashes []string
func (_e *DB_Expecter) GetTransactionsByHashes(hashes interface{}) *DB_GetTransactionsByHashes_Call {
	return &DB_GetTransactionsByHashes_Call{Call: _e.mock.On("GetTransactionsByHashes", hashes)}
}

func (_c *DB_GetTransactionsByHashes_Call) Run(run func(hashes []string)) *DB_GetTransactionsByHashes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *DB_GetTransactionsByHashes_Call) Return(_a0 []*models.Transaction, _a1 error) *DB_GetTransactionsByHashes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DB_GetTransactionsByHashes_Call) RunAndReturn(run func([]string) ([]*models.Transaction, error)) *DB_GetTransactionsByHashes_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUsername provides a mock function with given fields: username
func (_m *DB) GetUserByUsername(username string) (*models.User, error) {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.User, error)); ok {
		return rf(username)
	}
	if rf, ok := ret.Get(0).(func(string) *models.User); ok {
		r0 = rf(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DB_GetUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsername'
type DB_GetUserByUsername_Call struct {
	*mock.Call
}

// GetUserByUsername is a helper method to define mock.On call
//   - username string
func (_e *DB_Expecter) GetUserByUsername(username interface{}) *DB_GetUserByUsername_Call {
	return &DB_GetUserByUsername_Call{Call: _e.mock.On("GetUserByUsername", username)}
}

func (_c *DB_GetUserByUsername_Call) Run(run func(username string)) *DB_GetUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *DB_GetUserByUsername_Call) Return(_a0 *models.User, _a1 error) *DB_GetUserByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DB_GetUserByUsername_Call) RunAndReturn(run func(string) (*models.User, error)) *DB_GetUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserTransactions provides a mock function with given fields: userID
func (_m *DB) GetUserTransactions(userID string) ([]*models.Transaction, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserTransactions")
	}

	var r0 []*models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*models.Transaction, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []*models.Transaction); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DB_GetUserTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserTransactions'
type DB_GetUserTransactions_Call struct {
	*mock.Call
}

// GetUserTransactions is a helper method to define mock.On call
//   - userID string
func (_e *DB_Expecter) GetUserTransactions(userID interface{}) *DB_GetUserTransactions_Call {
	return &DB_GetUserTransactions_Call{Call: _e.mock.On("GetUserTransactions", userID)}
}

func (_c *DB_GetUserTransactions_Call) Run(run func(userID string)) *DB_GetUserTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *DB_GetUserTransactions_Call) Return(_a0 []*models.Transaction, _a1 error) *DB_GetUserTransactions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DB_GetUserTransactions_Call) RunAndReturn(run func(string) ([]*models.Transaction, error)) *DB_GetUserTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// SaveTransaction provides a mock function with given fields: transaction
func (_m *DB) SaveTransaction(transaction *models.Transaction) error {
	ret := _m.Called(transaction)

	if len(ret) == 0 {
		panic("no return value specified for SaveTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Transaction) error); ok {
		r0 = rf(transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DB_SaveTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveTransaction'
type DB_SaveTransaction_Call struct {
	*mock.Call
}

// SaveTransaction is a helper method to define mock.On call
//   - transaction *models.Transaction
func (_e *DB_Expecter) SaveTransaction(transaction interface{}) *DB_SaveTransaction_Call {
	return &DB_SaveTransaction_Call{Call: _e.mock.On("SaveTransaction", transaction)}
}

func (_c *DB_SaveTransaction_Call) Run(run func(transaction *models.Transaction)) *DB_SaveTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Transaction))
	})
	return _c
}

func (_c *DB_SaveTransaction_Call) Return(_a0 error) *DB_SaveTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DB_SaveTransaction_Call) RunAndReturn(run func(*models.Transaction) error) *DB_SaveTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewDB creates a new instance of DB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *DB {
	mock := &DB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
